set(ardupilot_sitl_gazebo_plugin_MESSAGE_FILES "")
set(ardupilot_sitl_gazebo_plugin_SERVICE_FILES "/home/user/armada3/Dev_code_version_SITL/ros_catkin_ws/src/ardupilot_sitl_gazebo_plugin/ardupilot_sitl_gazebo_plugin/srv/ReleaseApmLapseLock.srv;/home/user/armada3/Dev_code_version_SITL/ros_catkin_ws/src/ardupilot_sitl_gazebo_plugin/ardupilot_sitl_gazebo_plugin/srv/TakeApmLapseLock.srv")
