<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from ./src/ardupilot_sitl_gazebo_plugin/ardupilot_sitl_gazebo_plugin/urdf/armada.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<robot name="armada" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Properties -->
  <!-- 1 1 1 -->
  <!-- [kg] -->
  <!-- [m] 0.10 -->
  <!-- [m] 0.10 -->
  <!-- [m] -->
  <!-- [kg] -->
  <!-- [m] 0.1425  0.22 -->
  <!-- [m] 0.154  0.22 -->
  <!-- [m] 0.251  0.22 -->
  <!-- [m] 0.234  0.22 -->
  <!-- [m] 0.023-->
  <!-- [m] -->
  <!-- [kg.m/s^2] -->
  <!-- [m] -->
  <!-- [s] -->
  <!-- [s] -->
  <!-- [rad/s] -->
  <!-- Property Blocks -->
  <!-- inertia of a single rotor, assuming it is a cuboid. Height=3mm, width=15mm -->
  <!-- Included URDF Files -->
  <!-- <xacro:include filename="$(find rotors_description)/urdf/multirotor_base.xacro" /> -->
  <!-- Main multirotor link -->
  <!-- Rotor joint and link -->
  <!-- Instantiate multirotor_base_macro once -->
  <link name="base_link"/>
  <!-- Parachute attach point -${M_PI/2} -->
  <!--  <link name="chute_anchor_link">
    <origin xyz="-0.3 0 0 0" rpy="0 0 0" />
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
      </geometry>
    </visual>
  </link>
  <joint name="chute_anchor_link_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="chute_anchor_link" />
  </joint> -->
  <joint name="base_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="base_link_inertia"/>
  </joint>
  <link name="base_link_inertia">
    <inertial>
      <mass value="1.1"/>
      <!-- [kg] -->
      <origin xyz="0 0 0"/>
      <inertia ixx="0.0347563" ixy="0.0" ixz="0.0" iyy="0.0458929" iyz="0.0" izz="0.0977"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_drones/erlecopter.dae" scale="1 1 1"/>
        <!-- <box size="${body_width} ${body_width} ${body_height}"/> -->
        <!-- [m] [m] [m] -->
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.18 0.12 0.1"/>
        <!-- [m] [m] [m] -->
      </geometry>
    </collision>
  </link>
  <!-- attach multirotor_base_plugin to the base_link -->
  <gazebo>
    <plugin filename="librotors_gazebo_multirotor_base_plugin.so" name="rosbag">
      <robotNamespace>erlecopter</robotNamespace>
      <linkName>base_link</linkName>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
    </plugin>
  </gazebo>
  <!-- <gazebo reference="base_link"> -->
  <gazebo reference="base_link_inertia">
    <material>Gazebo/DarkGrey</material>
  </gazebo>
  <!-- Sonar sensor 
 <xacro:include filename="$(find ardupilot_sitl_gazebo_plugin)/urdf/sensors/real_sonar_sensor.urdf.xacro" />-->
  <!-- Configuration SIDE 
  <xacro:real_sonar_sensor
    name="real_sonar_front"
    parent="base_link"
    ros_topic="sonar_front"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="0.1 0 0" rpy="0 ${270*M_PI/180} 0"/>
  </xacro:real_sonar_sensor> 

  <xacro:real_sonar_sensor
    name="real_sonar_down"
    parent="base_link"
    ros_topic="sonar_down"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="-0.1 0 0" rpy="0 ${90*M_PI/180} 0"/>
  </xacro:real_sonar_sensor> 

  <xacro:real_sonar_sensor
    name="real_sonar_right"
    parent="base_link"
    ros_topic="sonar_right"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="0 -0.1 0" rpy="${270*M_PI/180} 0 0 "/>
  </xacro:real_sonar_sensor> 

  <xacro:real_sonar_sensor
    name="real_sonar_left"
    parent="base_link"
    ros_topic="sonar_left"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="0 0.1 0" rpy="${90*M_PI/180} 0 0"/>
  </xacro:real_sonar_sensor> -->
  <!-- Configuration FEET 
  <xacro:real_sonar_sensor
    name="real_sonar_front_left"
    parent="base_link"
    ros_topic="sonar_front_left"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="0.15 0.15 -0.03" rpy="0 ${270*M_PI/180} ${45*M_PI/180}"/>
  </xacro:real_sonar_sensor> 

  <xacro:real_sonar_sensor
    name="real_sonar_back_right"
    parent="base_link"
    ros_topic="sonar_back_right"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="-0.15 -0.15 -0.03" rpy="0 ${90*M_PI/180} ${45*M_PI/180}"/>
  </xacro:real_sonar_sensor> 

  <xacro:real_sonar_sensor
    name="real_sonar_front_right"
    parent="base_link"
    ros_topic="sonar_front_right"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="0.15 -0.15 -0.03" rpy="${270*M_PI/180} 0 ${45*M_PI/180} "/>
  </xacro:real_sonar_sensor> 

  <xacro:real_sonar_sensor
    name="real_sonar_back_left"
    parent="base_link"
    ros_topic="sonar_back_left"
    update_rate="10"
    min_range="0.02"
    max_range="7.65"
    radius="2.3"
    sensor_mesh="max_sonar_ez4/meshes/max_sonar_ez4.dae">
    <origin xyz="-0.15 0.15 -0.03" rpy="${90*M_PI/180} 0 ${45*M_PI/180}"/>
  </xacro:real_sonar_sensor> -->
  <!-- Lidar sensor -->
  <joint name="lidar_joint" type="fixed">
    <origin rpy="0 0 0" xyz="0.0 0.0 0.06"/>
    <parent link="base_link"/>
    <child link="lidar_link"/>
  </joint>
  <link name="lidar_link">
    <inertial>
      <mass value="0.001"/>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <inertia ixx="0.000000017" ixy="0" ixz="0" iyy="0.000000017" iyz="0" izz="0.000000017"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.03"/>
      <geometry>
        <!--<box size="0.01 0.01 0.01" /> -->
        <!-- <mesh filename="package://rotors_description/meshes/sonar_sensor/max_sonar_ez4.dae"/> -->
        <!--<mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/${sensor_mesh}"/>-->
        <mesh filename="file:///home/user/Dev_code_version_SITL/ros_catkin_ws/src/ardupilot_sitl_gazebo_plugin/ardupilot_sitl_gazebo_plugin/meshes/meshes_sensors/velodyne_VLP16/meshes/VLP16_base_1.dae"/>
        <!-- <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_sensor/lidar_lite_v2/meshes/lidar_lite_v2.dae"/> -->
      </geometry>
    </visual>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.03"/>
      <geometry>
        <!--<box size="0.01 0.01 0.01" /> -->
        <!-- <mesh filename="package://rotors_description/meshes/sonar_sensor/max_sonar_ez4.dae"/> -->
        <!--<mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/${sensor_mesh}"/>-->
        <mesh filename="file:///home/user/Dev_code_version_SITL/ros_catkin_ws/src/ardupilot_sitl_gazebo_plugin/ardupilot_sitl_gazebo_plugin/meshes/meshes_sensors/velodyne_VLP16/meshes/VLP16_base_2.dae"/>
        <!-- <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_sensor/lidar_lite_v2/meshes/lidar_lite_v2.dae"/> -->
      </geometry>
    </visual>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 -0.03"/>
      <geometry>
        <!--<box size="0.01 0.01 0.01" /> -->
        <!-- <mesh filename="package://rotors_description/meshes/sonar_sensor/max_sonar_ez4.dae"/> -->
        <!--<mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/${sensor_mesh}"/>-->
        <mesh filename="file:///home/user/Dev_code_version_SITL/ros_catkin_ws/src/ardupilot_sitl_gazebo_plugin/ardupilot_sitl_gazebo_plugin/meshes/meshes_sensors/velodyne_VLP16/meshes/VLP16_scan.dae"/>
        <!-- <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_sensor/lidar_lite_v2/meshes/lidar_lite_v2.dae"/> -->
      </geometry>
    </visual>
    <!--   <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.01 0.01 0.01" />
        </geometry>
      </collision> -->
  </link>
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="ray">
      <always_on>true</always_on>
      <update_rate>10</update_rate>
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>0.5</resolution>
            <min_angle>-3.14159265359</min_angle>
            <max_angle> 3.14159265359</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>1</resolution>
            <min_angle>-0.00872664625995</min_angle>
            <max_angle> 0.00872664625995</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.01</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <!-- <plugin name="gazebo_ros_${name}_controller" filename="librotors_gazebo_sonar_plugin.so">
          <gaussianNoise>0.005</gaussianNoise>
          <topicName>${ros_topic}</topicName>
          <frameId>scan_link</frameId>
        </plugin> -->
      <plugin filename="libgazebo_ros_laser.so" name="gazebo_ros_lidar_controller">
        <topicName>/scan</topicName>
        <!-- <frameName>scan_link</frameName> -->
        <frameName>lidar_link</frameName>
      </plugin>
    </sensor>
  </gazebo>
  <!-- Front facing camera -->
  <!-- <xacro:include filename="$(find ardupilot_sitl_gazebo_plugin)/urdf/sensors/generic_camera.urdf.xacro" />
  <xacro:generic_camera
    name="erlecopter/front"
    parent="base_link"
    ros_topic="image_front_raw"
    cam_info_topic="camera_front_info"
    update_rate="25"
    res_x="640"
    res_y="360"
    image_format="R8G8B8"
    hfov="81"
    framename="erlecopter_frontcam">
    <origin xyz="0.1 0.0 0.05" rpy="0 0 0"/>
</xacro:generic_camera>  -->
  <!-- Instantiate rotors -->
  <joint name="rotor_0_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0.141 -0.141 0.03"/>
    <axis xyz="0 0 1"/>
    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
    <parent link="base_link"/>
    <child link="rotor_0"/>
  </joint>
  <!-- TODO(ff): not currently set because it's not yet supported -->
  <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz>
      <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
  <link name="rotor_0">
    <inertial>
      <mass value="0.005"/>
      <!-- [kg] -->
      <inertia ixx="9.75e-07" ixy="0.0" ixz="0.0" iyy="0.0002400375" iyz="0.0" izz="0.0002409375"/>
    </inertial>
    <visual>
      <geometry>
        <!-- <cylinder length="0.005" radius="${radius_rotor}"/> -->
        <!-- [m] -->
        <!-- <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae" -->
        <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_drones/erlecopter_prop_ccw.dae" scale="1 1 1"/>
        <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.005" radius="0.12"/>
        <!-- [m] -->
      </geometry>
    </collision>
  </link>
  <gazebo>
    <plugin filename="librotors_gazebo_motor_model.so" name="front_right_motor_model">
      <robotNamespace>erlecopter</robotNamespace>
      <jointName>rotor_0_joint</jointName>
      <linkName>rotor_0</linkName>
      <turningDirection>ccw</turningDirection>
      <timeConstantUp>0.0125</timeConstantUp>
      <timeConstantDown>0.025</timeConstantDown>
      <maxRotVelocity>838</maxRotVelocity>
      <motorConstant>8.54858e-06</motorConstant>
      <momentConstant>0.016</momentConstant>
      <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
      <motorNumber>0</motorNumber>
      <rotorDragCoefficient>8.06428e-05</rotorDragCoefficient>
      <rollingMomentCoefficient>1e-06</rollingMomentCoefficient>
      <motorSpeedPubTopic>motor_speed/0</motorSpeedPubTopic>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
    </plugin>
  </gazebo>
  <gazebo reference="rotor_0">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <joint name="rotor_1_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-0.141 0.141 0.03"/>
    <axis xyz="0 0 1"/>
    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
    <parent link="base_link"/>
    <child link="rotor_1"/>
  </joint>
  <!-- TODO(ff): not currently set because it's not yet supported -->
  <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz>
      <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
  <link name="rotor_1">
    <inertial>
      <mass value="0.005"/>
      <!-- [kg] -->
      <inertia ixx="9.75e-07" ixy="0.0" ixz="0.0" iyy="0.0002400375" iyz="0.0" izz="0.0002409375"/>
    </inertial>
    <visual>
      <geometry>
        <!-- <cylinder length="0.005" radius="${radius_rotor}"/> -->
        <!-- [m] -->
        <!-- <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae" -->
        <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_drones/erlecopter_prop_ccw.dae" scale="1 1 1"/>
        <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.005" radius="0.12"/>
        <!-- [m] -->
      </geometry>
    </collision>
  </link>
  <gazebo>
    <plugin filename="librotors_gazebo_motor_model.so" name="back_left_motor_model">
      <robotNamespace>erlecopter</robotNamespace>
      <jointName>rotor_1_joint</jointName>
      <linkName>rotor_1</linkName>
      <turningDirection>ccw</turningDirection>
      <timeConstantUp>0.0125</timeConstantUp>
      <timeConstantDown>0.025</timeConstantDown>
      <maxRotVelocity>838</maxRotVelocity>
      <motorConstant>8.54858e-06</motorConstant>
      <momentConstant>0.016</momentConstant>
      <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
      <motorNumber>1</motorNumber>
      <rotorDragCoefficient>8.06428e-05</rotorDragCoefficient>
      <rollingMomentCoefficient>1e-06</rollingMomentCoefficient>
      <motorSpeedPubTopic>motor_speed/1</motorSpeedPubTopic>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
    </plugin>
  </gazebo>
  <gazebo reference="rotor_1">
    <material>Gazebo/Black</material>
  </gazebo>
  <joint name="rotor_2_joint" type="continuous">
    <origin rpy="0 0 0" xyz="0.141 0.141 0.03"/>
    <axis xyz="0 0 1"/>
    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
    <parent link="base_link"/>
    <child link="rotor_2"/>
  </joint>
  <!-- TODO(ff): not currently set because it's not yet supported -->
  <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz>
      <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
  <link name="rotor_2">
    <inertial>
      <mass value="0.005"/>
      <!-- [kg] -->
      <inertia ixx="9.75e-07" ixy="0.0" ixz="0.0" iyy="0.0002400375" iyz="0.0" izz="0.0002409375"/>
    </inertial>
    <visual>
      <geometry>
        <!-- <cylinder length="0.005" radius="${radius_rotor}"/> -->
        <!-- [m] -->
        <!-- <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae" -->
        <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_drones/erlecopter_prop_cw.dae" scale="1 1 1"/>
        <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.005" radius="0.12"/>
        <!-- [m] -->
      </geometry>
    </collision>
  </link>
  <gazebo>
    <plugin filename="librotors_gazebo_motor_model.so" name="front_left_motor_model">
      <robotNamespace>erlecopter</robotNamespace>
      <jointName>rotor_2_joint</jointName>
      <linkName>rotor_2</linkName>
      <turningDirection>cw</turningDirection>
      <timeConstantUp>0.0125</timeConstantUp>
      <timeConstantDown>0.025</timeConstantDown>
      <maxRotVelocity>838</maxRotVelocity>
      <motorConstant>8.54858e-06</motorConstant>
      <momentConstant>0.016</momentConstant>
      <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
      <motorNumber>2</motorNumber>
      <rotorDragCoefficient>8.06428e-05</rotorDragCoefficient>
      <rollingMomentCoefficient>1e-06</rollingMomentCoefficient>
      <motorSpeedPubTopic>motor_speed/2</motorSpeedPubTopic>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
    </plugin>
  </gazebo>
  <gazebo reference="rotor_2">
    <material>Gazebo/Yellow</material>
  </gazebo>
  <joint name="rotor_3_joint" type="continuous">
    <origin rpy="0 0 0" xyz="-0.141 -0.141 0.03"/>
    <axis xyz="0 0 1"/>
    <!-- TODO(ff): not currently set because it's not yet supported -->
    <!-- <limit effort="2000" velocity="${max_rot_velocity}" /> -->
    <parent link="base_link"/>
    <child link="rotor_3"/>
  </joint>
  <!-- TODO(ff): not currently set because it's not yet supported -->
  <!-- <gazebo reference="rotor_${motor_number}_joint"> <axis> <xyz>0 0 1</xyz>
      <limit> <velocity> ${max_rot_velocity} </velocity> </limit> </axis> </gazebo> -->
  <link name="rotor_3">
    <inertial>
      <mass value="0.005"/>
      <!-- [kg] -->
      <inertia ixx="9.75e-07" ixy="0.0" ixz="0.0" iyy="0.0002400375" iyz="0.0" izz="0.0002409375"/>
    </inertial>
    <visual>
      <geometry>
        <!-- <cylinder length="0.005" radius="${radius_rotor}"/> -->
        <!-- [m] -->
        <!-- <mesh filename="package://rotors_description/meshes/propeller_${direction}.dae" -->
        <mesh filename="package://ardupilot_sitl_gazebo_plugin/meshes/meshes_drones/erlecopter_prop_cw.dae" scale="1 1 1"/>
        <!-- <box size="${2*radius_rotor} 0.01 0.005"/> -->
      </geometry>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.005" radius="0.12"/>
        <!-- [m] -->
      </geometry>
    </collision>
  </link>
  <gazebo>
    <plugin filename="librotors_gazebo_motor_model.so" name="back_right_motor_model">
      <robotNamespace>erlecopter</robotNamespace>
      <jointName>rotor_3_joint</jointName>
      <linkName>rotor_3</linkName>
      <turningDirection>cw</turningDirection>
      <timeConstantUp>0.0125</timeConstantUp>
      <timeConstantDown>0.025</timeConstantDown>
      <maxRotVelocity>838</maxRotVelocity>
      <motorConstant>8.54858e-06</motorConstant>
      <momentConstant>0.016</momentConstant>
      <commandSubTopic>gazebo/command/motor_speed</commandSubTopic>
      <motorNumber>3</motorNumber>
      <rotorDragCoefficient>8.06428e-05</rotorDragCoefficient>
      <rollingMomentCoefficient>1e-06</rollingMomentCoefficient>
      <motorSpeedPubTopic>motor_speed/3</motorSpeedPubTopic>
      <rotorVelocitySlowdownSim>10</rotorVelocitySlowdownSim>
    </plugin>
  </gazebo>
  <gazebo reference="rotor_3">
    <material>Gazebo/Black</material>
  </gazebo>
</robot>
