TrajectoryPlannerROS:
  max_vel_x: 0.75  #2.25
  min_vel_x: 0.0   #-2.25
  max_vel_y: 0.75
  min_vel_y: 0.0
  max_rotational_vel: 20.0
  min_in_place_rotational_vel: -1.0
  min_in_place_vel_theta: -1.0  #0.5
  max_vel_theta: 10.0  #0.5
  min_vel_theta: -10.0
  acc_lim_theta: 10.2  #0.2
  acc_lim_x: 0.5  #1.2
  acc_lim_y: 0.5  #1.2
  holonomic_robot: true



