DWAPlannerROS:

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05  # 0.2
  xy_goal_tolerance: 0.1 # 0.50
  # latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 2.0       # 1.7
  vx_samples: 20       # 3
  vy_samples: 20       # diff drive robot, there is only one sample
  vtheta_samples: 30  # 20
  sim_granularity: 0.025 #0.0125  # 0.025


# Trajectory Scoring Parameters
  path_distance_bias: 45.0      # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 20.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.02            # 0.005   - weighting for how much the controller should avoid obstacles
  
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #500  # 0.05   - how far to travel before resetting oscillation flags

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: map #map  


