local_costmap:
  global_frame: map #odom
  robot_base_frame: base_link
  update_frequency: 5.0 #1
  publish_frequency: 2.0 #1
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.005
  tranform_tolerance: 0.5
  planner_frequency: 10.0
  planner_patiente: 10.0
